### ISSUE TITLE
KeyError: 'id' while running main.py

### ISSUE THREAD

**Issue by elyorman** [sooftware/KsponSpeech-preprocess#2]
`base) C:\Users\Admin\ELYOR\kospeech\preprocessing\KsponSpeech-preprocess-master>python main.py
preprocess started..
create_char_labels started..
create_script started..
Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas\_libs\index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 22, in <module>
    create_script(opt.dataset_path, opt.script_prefix)
  File "C:\Users\Admin\ELYOR\kospeech\preprocessing\KsponSpeech-preprocess-master\preprocess\preprocess.py", line 64, in create_script
    char2id, id2char = load_label('aihub_labels.csv')
  File "C:\Users\Admin\ELYOR\kospeech\preprocessing\KsponSpeech-preprocess-master\preprocess\functional.py", line 9, in load_label
    id_list = ch_labels["id"]
  File "C:\Users\Admin\anaconda3\lib\site-packages\pandas\core\frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\Admin\anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas\_libs\index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'id'`
I have been trying to fix it but no luck so for. Hope you could help me with it.

**Comment by sooftware** [comment]
Can you show me how the aihub_labels.csv file is organized?

**Comment by elyorman** [comment]
![Screenshot from 2020-07-17 15-58-44](https://user-images.githubusercontent.com/60263344/87758952-712a0080-c848-11ea-9845-d835a894083b.png)
I think it's well organized

**Comment by sooftware** [comment]
Can you show me result of print 'ch_labels' variable in load_label() func?

**Comment by elyorman** [comment]
![Screenshot from 2020-07-17 16-41-26](https://user-images.githubusercontent.com/60263344/87762663-725e2c00-c84e-11ea-97e8-8026d42fd134.png)
the same KeyError here too

**Comment by sooftware** [comment]
Please show me result of print 'ch_labels' variable

**Comment by elyorman** [comment]
![Screenshot from 2020-07-17 16-43-58](https://user-images.githubusercontent.com/60263344/87763244-6fb00680-c84f-11ea-9ccc-d0790ca6d5cb.png)

**Comment by sooftware** [comment]
```python
>>> ch_labels.head()  
result
```
I think the column is broken.    
I want to check properly in data frame format.  
Show me the result.

**Comment by elyorman** [comment]
![Screenshot from 2020-07-17 17-11-09](https://user-images.githubusercontent.com/60263344/87763940-886cec00-c850-11ea-86b3-fea15c9fe810.png)
yeah it looks like that

**Comment by sooftware** [comment]
Now that we've found the problem, we just need to figure out where the problem came from.  
I think the format is lumped when you save it as a data frame.  
I don't think I can answer quickly because I'm watching from time to time doing other things. I would appreciate it if you could check the code on the side where you save it. I will check as soon as possible.

**Comment by elyorman** [comment]
Okay thank you for your time. I did not  make any change to your code except for `ch_labels = pd.read_csv(filepath, encoding="cp949")` >>ch_labels = pd.read_csv(filepath, encoding="UTF8") when I had to fix another error. Maybe this was the reason. Will leave the solution when I have found it.

**Comment by sooftware** [comment]
Or you can check this page : https://github.com/sooftware/KoSpeech/wiki/Preparation-before-Training

**Comment by sooftware** [comment]
Thank you for leaving an issue. It is a repo that organizes the code in the above link so that it can be rotated at once, so if there is anything different from the code in the link, it would be good to check.
